/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package org.javamexico.blockchain

import spock.lang.Specification

class AppTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new App()

        when:
        def a = true

        then:
        a == true
    }
}
